import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LocalizationProvider from "@/utils/localization-provider";
import ThemeProvider from "@/theme";
import {MotionLazy} from "@/components/animate/MotionLazy";
import ProgressBar from "@/components/progress-bar";
import SettingsDrawer from "@/components/settings/drawer/SettingsDrawer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocalizationProvider>
          <ThemeProvider>
            <MotionLazy>
              <ProgressBar />
              <SettingsDrawer />
              {children}
            </MotionLazy>
          </ThemeProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}
